<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fun.fengwk.convention4j</groupId>
        <artifactId>convention4j-parent</artifactId>
        <version>1.2.1</version>
    </parent>

    <groupId>fun.fengwk.kk-studio</groupId>
    <artifactId>kk-studio-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>share</module>
        <module>core</module>
        <module>web</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>utf-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>utf-8</project.reporting.outputEncoding>
        <kk-studio.version>1.0.0</kk-studio.version>
        <gateway.version>1.0.8</gateway.version>
        <langchain4j.version>1.11.7</langchain4j.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>fun.fengwk.kk-studio</groupId>
                <artifactId>kk-studio-share</artifactId>
                <version>${kk-studio.version}</version>
            </dependency>
            <dependency>
                <groupId>fun.fengwk.kk-studio</groupId>
                <artifactId>kk-studio-core</artifactId>
                <version>${kk-studio.version}</version>
            </dependency>
            <dependency>
                <groupId>fun.fengwk.kk-studio</groupId>
                <artifactId>kk-studio-web</artifactId>
                <version>${kk-studio.version}</version>
            </dependency>
            <dependency>
                <groupId>fun.fengwk.gateway</groupId>
                <artifactId>gateway-share</artifactId>
                <version>${gateway.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain4j.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
