import type {
  SystemSettingsDTO,
  SystemSettingsSchemaDTO,
} from '@/shared/api/contracts/system-settings'

/**
 * 平台环境与资源默认字节上限：16 MiB (16777216)。
 */
export const DEFAULT_MAX_RESOURCE_BYTES = '16777216'

/**
 * 测试基座：与 share DTO / V1 默认行一致的完整 GET {@code /api/settings} 响应形状。
 *
 * 仅用于前端测试验证「严格契约字段映射 / 聚合 hydration / 完整聚合 CAS PUT」，
 * 不是前端运行时默认值（生产 draft 只从 GET 权威数据派生）。
 */
export function makeSettingsDto(overrides: { version?: string } = {}): SystemSettingsDTO {
  return {
    tool: {
      permission: {
        'base.write': [{ pattern: '*', action: 'ask' }],
        'base.edit': [{ pattern: '*', action: 'ask' }],
        'base.bash': [{ pattern: '*', action: 'ask' }],
      },
      defaultYolo: false,
      modelGatewayBusyRetryMillis: '5000',
      toolGatewayBusyRetryMillis: '1000',
      toolGatewayOverloadRetryMillis: '5000',
      skillLoadTimeoutMillis: '30000',
    },
    aiRuntime: {
      retryMaxRetries: 3,
      retryBackoffStrategy: 'EXPONENTIAL',
      retryBaseDelayMillis: '2000',
      retryMaxDelayMillis: '60000',
      compactionKeepRecentTokens: 20000,
      compactionFallbackModel: null,
      subagentMaxDepth: 2,
      subagentMaxConcurrency: 10,
      subagentMaxTotalConcurrency: 0,
      subagentIdleTimeoutMillis: '0',
      subagentMaxTurns: 50,
    },
    environment: {
      maxResourceBytes: DEFAULT_MAX_RESOURCE_BYTES,
      heartbeatTimeoutMillis: '60000',
    },
    integrations: {
      comfyui: {
        enabled: false,
        baseUrl: null,
        connectTimeoutMillis: '10000',
        readTimeoutMillis: '30000',
        websocketTimeoutMillis: '1800000',
        maxInputFileBytes: '52428800',
      },
      openCliHub: {
        enabled: false,
        baseUrl: null,
        connectTimeoutMillis: '5000',
        requestTimeoutMillis: '120000',
        longPollTimeoutMillis: '130000',
        streamBufferBytes: 16384,
        maxJsonResponseBytes: 524288,
        maxErrorResponseBytes: 4096,
        maxOutputChars: 65535,
      },
      seedance: {
        enabled: false,
        workspaceId: null,
        retry: 0,
        hubExecutionTimeoutMillis: '600000',
        statusPollIntervalMillis: '30000',
        maxWaitMillis: '1800000',
      },
      gptImage2: {
        paidEnabled: false,
        askTimeoutSeconds: 900,
        hubExecutionTimeoutMillis: '960000',
        maxWaitMillis: '1200000',
      },
      minimaxH3: {
        enabled: false,
        promptAgentName: null,
        promptMaxWaitMillis: '600000',
        comfyBaseUrl: null,
        comfyConnectTimeoutMillis: '10000',
        comfyRequestTimeoutMillis: '30000',
        comfyPollIntervalMillis: '2000',
        comfyMaxWaitMillis: '1800000',
      },
    },
    storageMedia: {
      uploadExpiresSeconds: '3600',
      s3PresignDefaultExpiresSeconds: '600',
      s3PresignMaxExpiresSeconds: '3600',
      canvasMediaProcessTimeoutMillis: '30000',
      thumbnailMaxDimension: 512,
      thumbnailQuality: 80,
    },
    advanced: {
      resourceMaxBytes: DEFAULT_MAX_RESOURCE_BYTES,
      processorLeaseDurationMillis: '30000',
      processorHeartbeatIntervalMillis: '10000',
      threadResolveFailureDelayMillis: '1000',
      modelDispatchBusyFallbackDelayMillis: '1000',
      toolPreflightFailureDelayMillis: '1000',
      toolDispatchBusyFallbackDelayMillis: '1000',
      applicationEventQueueCapacity: 512,
      applicationEventMaxBytes: '2097152',
      applicationEventSendTimeoutMillis: '10000',
      applicationEventHeartbeatIntervalMillis: '20000',
      postgresqlWorkNotificationPollMillis: '5000',
      postgresqlWorkReconnectBackoffMillis: '1000',
    },
    version: overrides.version ?? '0',
    createTime: '2026-01-01T00:00:00Z',
    updateTime: '2026-01-01T00:00:00Z',
  }
}

/**
 * 测试基座：与 {@code GET /api/settings/schema} 响应形状一致的 schema。
 *
 * 字段 path/分组与 core 的 SystemSettingsSchemaProvider 一一对应；测试用它驱动渲染与 fail-closed 校验。
 */
export function makeSettingsSchema(): SystemSettingsSchemaDTO {
  return {
    sections: [
      {
        key: 'aiRuntime',
        labelKey: 'settings.tabs.aiRuntime',
        descriptionKey: 'settings.section.aiRuntime.description',
        restartRequired: false,
        groups: [
          {
            key: 'aiRuntime.retry',
            labelKey: 'settings.section.aiRuntime.retry.title',
            descriptionKey: 'settings.section.aiRuntime.retry.description',
            restartRequired: false,
            applyTiming: 'NEXT_INVOCATION',
            fields: [
              {
                path: 'aiRuntime.retryMaxRetries',
                labelKey: 'settings.field.aiRuntime.retryMaxRetries',
                hintKey: 'settings.field.aiRuntime.retryMaxRetries.hint',
                type: 'INTEGER',
                nullable: false,
                min: 0,
                max: null,
                options: null,
              },
              {
                path: 'aiRuntime.retryBackoffStrategy',
                labelKey: 'settings.field.aiRuntime.retryBackoffStrategy',
                hintKey: 'settings.field.aiRuntime.retryBackoffStrategy.hint',
                type: 'ENUM',
                nullable: false,
                min: null,
                max: null,
                options: [
                  { value: 'FIXED', labelKey: 'settings.option.retryBackoff.fixed' },
                  { value: 'EXPONENTIAL', labelKey: 'settings.option.retryBackoff.exponential' },
                ],
              },
              {
                path: 'aiRuntime.retryBaseDelayMillis',
                labelKey: 'settings.field.aiRuntime.retryBaseDelayMillis',
                hintKey: 'settings.field.aiRuntime.retryBaseDelayMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'aiRuntime.retryMaxDelayMillis',
                labelKey: 'settings.field.aiRuntime.retryMaxDelayMillis',
                hintKey: 'settings.field.aiRuntime.retryMaxDelayMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'aiRuntime.compaction',
            labelKey: 'settings.section.aiRuntime.compaction.title',
            descriptionKey: 'settings.section.aiRuntime.compaction.description',
            restartRequired: false,
            applyTiming: 'NEXT_INVOCATION',
            fields: [
              {
                path: 'aiRuntime.compactionKeepRecentTokens',
                labelKey: 'settings.field.aiRuntime.compactionKeepRecentTokens',
                hintKey: 'settings.field.aiRuntime.compactionKeepRecentTokens.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'aiRuntime.compactionFallbackModel',
                labelKey: 'settings.field.aiRuntime.compactionFallbackModel',
                hintKey: 'settings.field.aiRuntime.compactionFallbackModel.hint',
                type: 'MODEL_SELECTION',
                nullable: true,
                min: null,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'aiRuntime.subagent',
            labelKey: 'settings.section.aiRuntime.subagent.title',
            descriptionKey: 'settings.section.aiRuntime.subagent.description',
            restartRequired: false,
            applyTiming: 'NEXT_INVOCATION',
            fields: [
              {
                path: 'aiRuntime.subagentMaxDepth',
                labelKey: 'settings.field.aiRuntime.subagentMaxDepth',
                hintKey: 'settings.field.aiRuntime.subagentMaxDepth.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'aiRuntime.subagentMaxConcurrency',
                labelKey: 'settings.field.aiRuntime.subagentMaxConcurrency',
                hintKey: 'settings.field.aiRuntime.subagentMaxConcurrency.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'aiRuntime.subagentMaxTotalConcurrency',
                labelKey: 'settings.field.aiRuntime.subagentMaxTotalConcurrency',
                hintKey: 'settings.field.aiRuntime.subagentMaxTotalConcurrency.hint',
                type: 'INTEGER',
                nullable: false,
                min: 0,
                max: null,
                options: null,
              },
              {
                path: 'aiRuntime.subagentIdleTimeoutMillis',
                labelKey: 'settings.field.aiRuntime.subagentIdleTimeoutMillis',
                hintKey: 'settings.field.aiRuntime.subagentIdleTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 0,
                max: null,
                options: null,
              },
              {
                path: 'aiRuntime.subagentMaxTurns',
                labelKey: 'settings.field.aiRuntime.subagentMaxTurns',
                hintKey: 'settings.field.aiRuntime.subagentMaxTurns.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
        ],
      },
      {
        key: 'tool',
        labelKey: 'settings.tabs.toolsPermissions',
        descriptionKey: 'settings.section.tool.description',
        restartRequired: false,
        groups: [
          {
            key: 'tool.permission',
            labelKey: 'settings.section.tool.permission.title',
            descriptionKey: 'settings.section.tool.permission.description',
            restartRequired: false,
            applyTiming: 'NEXT_INVOCATION',
            fields: [
              {
                path: 'tool.permission',
                labelKey: 'settings.section.tool.permission.title',
                hintKey: 'settings.field.tool.permission.hint',
                type: 'PERMISSION',
                nullable: false,
                min: null,
                max: null,
                options: [
                  { value: 'allow', labelKey: 'settings.permission.action.allow' },
                  { value: 'ask', labelKey: 'settings.permission.action.ask' },
                  { value: 'deny', labelKey: 'settings.permission.action.deny' },
                ],
              },
            ],
          },
          {
            key: 'tool.yolo',
            labelKey: 'settings.section.tool.yolo.title',
            descriptionKey: 'settings.section.tool.yolo.description',
            restartRequired: false,
            applyTiming: 'NEXT_CHAT',
            fields: [
              {
                path: 'tool.defaultYolo',
                labelKey: 'settings.field.tool.defaultYolo',
                hintKey: 'settings.field.tool.defaultYolo.hint',
                type: 'BOOLEAN',
                nullable: false,
                min: null,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'tool.gateway',
            labelKey: 'settings.section.tool.gateway.title',
            descriptionKey: 'settings.section.tool.gateway.description',
            restartRequired: false,
            applyTiming: 'NEXT_INVOCATION',
            fields: [
              {
                path: 'tool.modelGatewayBusyRetryMillis',
                labelKey: 'settings.field.tool.modelGatewayBusyRetryMillis',
                hintKey: 'settings.field.tool.modelGatewayBusyRetryMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'tool.toolGatewayBusyRetryMillis',
                labelKey: 'settings.field.tool.toolGatewayBusyRetryMillis',
                hintKey: 'settings.field.tool.toolGatewayBusyRetryMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'tool.toolGatewayOverloadRetryMillis',
                labelKey: 'settings.field.tool.toolGatewayOverloadRetryMillis',
                hintKey: 'settings.field.tool.toolGatewayOverloadRetryMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'tool.skillLoadTimeoutMillis',
                labelKey: 'settings.field.tool.skillLoadTimeoutMillis',
                hintKey: 'settings.field.tool.skillLoadTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
        ],
      },
      {
        key: 'environment',
        labelKey: 'settings.tabs.environment',
        descriptionKey: 'settings.section.environment.description',
        restartRequired: false,
        groups: [
          {
            key: 'environment.runtime',
            labelKey: 'settings.section.environment.runtime.title',
            descriptionKey: 'settings.section.environment.runtime.description',
            restartRequired: false,
            applyTiming: 'NEXT_INVOCATION',
            fields: [
              {
                path: 'environment.maxResourceBytes',
                labelKey: 'settings.field.environment.maxResourceBytes',
                hintKey: 'settings.field.environment.maxResourceBytes.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'environment.heartbeatTimeoutMillis',
                labelKey: 'settings.field.environment.heartbeatTimeoutMillis',
                hintKey: 'settings.field.environment.heartbeatTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
        ],
      },
      {
        key: 'integrations',
        labelKey: 'settings.tabs.integrations',
        descriptionKey: 'settings.section.integrations.description',
        restartRequired: true,
        groups: [
          {
            key: 'integrations.comfyui',
            labelKey: 'settings.section.integrations.comfyui.title',
            descriptionKey: 'settings.section.integrations.comfyui.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'integrations.comfyui.enabled',
                labelKey: 'settings.field.integrations.comfyui.enabled',
                hintKey: 'settings.field.integrations.comfyui.enabled.hint',
                type: 'BOOLEAN',
                nullable: false,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.comfyui.baseUrl',
                labelKey: 'settings.field.integrations.comfyui.baseUrl',
                hintKey: 'settings.field.integrations.comfyui.baseUrl.hint',
                type: 'TEXT',
                nullable: true,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.comfyui.connectTimeoutMillis',
                labelKey: 'settings.field.integrations.comfyui.connectTimeoutMillis',
                hintKey: 'settings.field.integrations.comfyui.connectTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'integrations.comfyui.readTimeoutMillis',
                labelKey: 'settings.field.integrations.comfyui.readTimeoutMillis',
                hintKey: 'settings.field.integrations.comfyui.readTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'integrations.comfyui.websocketTimeoutMillis',
                labelKey: 'settings.field.integrations.comfyui.websocketTimeoutMillis',
                hintKey: 'settings.field.integrations.comfyui.websocketTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'integrations.comfyui.maxInputFileBytes',
                labelKey: 'settings.field.integrations.comfyui.maxInputFileBytes',
                hintKey: 'settings.field.integrations.comfyui.maxInputFileBytes.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'integrations.openCliHub',
            labelKey: 'settings.section.integrations.openCliHub.title',
            descriptionKey: 'settings.section.integrations.openCliHub.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'integrations.openCliHub.enabled',
                labelKey: 'settings.field.integrations.openCliHub.enabled',
                hintKey: 'settings.field.integrations.openCliHub.enabled.hint',
                type: 'BOOLEAN',
                nullable: false,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.openCliHub.baseUrl',
                labelKey: 'settings.field.integrations.openCliHub.baseUrl',
                hintKey: 'settings.field.integrations.openCliHub.baseUrl.hint',
                type: 'TEXT',
                nullable: true,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.openCliHub.connectTimeoutMillis',
                labelKey: 'settings.field.integrations.openCliHub.connectTimeoutMillis',
                hintKey: 'settings.field.integrations.openCliHub.connectTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: 120000,
                options: null,
              },
              {
                path: 'integrations.openCliHub.requestTimeoutMillis',
                labelKey: 'settings.field.integrations.openCliHub.requestTimeoutMillis',
                hintKey: 'settings.field.integrations.openCliHub.requestTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1000,
                max: 1800000,
                options: null,
              },
              {
                path: 'integrations.openCliHub.longPollTimeoutMillis',
                labelKey: 'settings.field.integrations.openCliHub.longPollTimeoutMillis',
                hintKey: 'settings.field.integrations.openCliHub.longPollTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 121000,
                max: 600000,
                options: null,
              },
              {
                path: 'integrations.openCliHub.streamBufferBytes',
                labelKey: 'settings.field.integrations.openCliHub.streamBufferBytes',
                hintKey: 'settings.field.integrations.openCliHub.streamBufferBytes.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1024,
                max: 1048576,
                options: null,
              },
              {
                path: 'integrations.openCliHub.maxJsonResponseBytes',
                labelKey: 'settings.field.integrations.openCliHub.maxJsonResponseBytes',
                hintKey: 'settings.field.integrations.openCliHub.maxJsonResponseBytes.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1024,
                max: 4194304,
                options: null,
              },
              {
                path: 'integrations.openCliHub.maxErrorResponseBytes',
                labelKey: 'settings.field.integrations.openCliHub.maxErrorResponseBytes',
                hintKey: 'settings.field.integrations.openCliHub.maxErrorResponseBytes.hint',
                type: 'INTEGER',
                nullable: false,
                min: 256,
                max: 65536,
                options: null,
              },
              {
                path: 'integrations.openCliHub.maxOutputChars',
                labelKey: 'settings.field.integrations.openCliHub.maxOutputChars',
                hintKey: 'settings.field.integrations.openCliHub.maxOutputChars.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1024,
                max: 1000000,
                options: null,
              },
            ],
          },
          {
            key: 'integrations.seedance',
            labelKey: 'settings.section.integrations.seedance.title',
            descriptionKey: 'settings.section.integrations.seedance.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'integrations.seedance.enabled',
                labelKey: 'settings.field.integrations.seedance.enabled',
                hintKey: 'settings.field.integrations.seedance.enabled.hint',
                type: 'BOOLEAN',
                nullable: false,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.seedance.workspaceId',
                labelKey: 'settings.field.integrations.seedance.workspaceId',
                hintKey: 'settings.field.integrations.seedance.workspaceId.hint',
                type: 'TEXT',
                nullable: true,
                min: null,
                max: 256,
                options: null,
              },
              {
                path: 'integrations.seedance.retry',
                labelKey: 'settings.field.integrations.seedance.retry',
                hintKey: 'settings.field.integrations.seedance.retry.hint',
                type: 'INTEGER',
                nullable: false,
                min: 0,
                max: 5,
                options: null,
              },
              {
                path: 'integrations.seedance.hubExecutionTimeoutMillis',
                labelKey: 'settings.field.integrations.seedance.hubExecutionTimeoutMillis',
                hintKey: 'settings.field.integrations.seedance.hubExecutionTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1000,
                max: 1800000,
                options: null,
              },
              {
                path: 'integrations.seedance.statusPollIntervalMillis',
                labelKey: 'settings.field.integrations.seedance.statusPollIntervalMillis',
                hintKey: 'settings.field.integrations.seedance.statusPollIntervalMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: 300000,
                options: null,
              },
              {
                path: 'integrations.seedance.maxWaitMillis',
                labelKey: 'settings.field.integrations.seedance.maxWaitMillis',
                hintKey: 'settings.field.integrations.seedance.maxWaitMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1000,
                max: 14400000,
                options: null,
              },
            ],
          },
          {
            key: 'integrations.gptImage2',
            labelKey: 'settings.section.integrations.gptImage2.title',
            descriptionKey: 'settings.section.integrations.gptImage2.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'integrations.gptImage2.paidEnabled',
                labelKey: 'settings.field.integrations.gptImage2.paidEnabled',
                hintKey: 'settings.field.integrations.gptImage2.paidEnabled.hint',
                type: 'BOOLEAN',
                nullable: false,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.gptImage2.askTimeoutSeconds',
                labelKey: 'settings.field.integrations.gptImage2.askTimeoutSeconds',
                hintKey: 'settings.field.integrations.gptImage2.askTimeoutSeconds.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: 1740,
                options: null,
              },
              {
                path: 'integrations.gptImage2.hubExecutionTimeoutMillis',
                labelKey: 'settings.field.integrations.gptImage2.hubExecutionTimeoutMillis',
                hintKey: 'settings.field.integrations.gptImage2.hubExecutionTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 31000,
                max: 1800000,
                options: null,
              },
              {
                path: 'integrations.gptImage2.maxWaitMillis',
                labelKey: 'settings.field.integrations.gptImage2.maxWaitMillis',
                hintKey: 'settings.field.integrations.gptImage2.maxWaitMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1000,
                max: 7200000,
                options: null,
              },
            ],
          },
          {
            key: 'integrations.minimaxH3',
            labelKey: 'settings.section.integrations.minimaxH3.title',
            descriptionKey: 'settings.section.integrations.minimaxH3.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'integrations.minimaxH3.enabled',
                labelKey: 'settings.field.integrations.minimaxH3.enabled',
                hintKey: 'settings.field.integrations.minimaxH3.enabled.hint',
                type: 'BOOLEAN',
                nullable: false,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.minimaxH3.promptAgentName',
                labelKey: 'settings.field.integrations.minimaxH3.promptAgentName',
                hintKey: 'settings.field.integrations.minimaxH3.promptAgentName.hint',
                type: 'TEXT',
                nullable: true,
                min: null,
                max: 64,
                options: null,
              },
              {
                path: 'integrations.minimaxH3.promptMaxWaitMillis',
                labelKey: 'settings.field.integrations.minimaxH3.promptMaxWaitMillis',
                hintKey: 'settings.field.integrations.minimaxH3.promptMaxWaitMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: 1800000,
                options: null,
              },
              {
                path: 'integrations.minimaxH3.comfyBaseUrl',
                labelKey: 'settings.field.integrations.minimaxH3.comfyBaseUrl',
                hintKey: 'settings.field.integrations.minimaxH3.comfyBaseUrl.hint',
                type: 'TEXT',
                nullable: true,
                min: null,
                max: null,
                options: null,
              },
              {
                path: 'integrations.minimaxH3.comfyConnectTimeoutMillis',
                labelKey: 'settings.field.integrations.minimaxH3.comfyConnectTimeoutMillis',
                hintKey: 'settings.field.integrations.minimaxH3.comfyConnectTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: 60000,
                options: null,
              },
              {
                path: 'integrations.minimaxH3.comfyRequestTimeoutMillis',
                labelKey: 'settings.field.integrations.minimaxH3.comfyRequestTimeoutMillis',
                hintKey: 'settings.field.integrations.minimaxH3.comfyRequestTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: 300000,
                options: null,
              },
              {
                path: 'integrations.minimaxH3.comfyPollIntervalMillis',
                labelKey: 'settings.field.integrations.minimaxH3.comfyPollIntervalMillis',
                hintKey: 'settings.field.integrations.minimaxH3.comfyPollIntervalMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: 60000,
                options: null,
              },
              {
                path: 'integrations.minimaxH3.comfyMaxWaitMillis',
                labelKey: 'settings.field.integrations.minimaxH3.comfyMaxWaitMillis',
                hintKey: 'settings.field.integrations.minimaxH3.comfyMaxWaitMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: 7200000,
                options: null,
              },
            ],
          },
        ],
      },
      {
        key: 'storageMedia',
        labelKey: 'settings.tabs.storageMedia',
        descriptionKey: 'settings.section.storageMedia.description',
        restartRequired: true,
        groups: [
          {
            key: 'storageMedia.upload',
            labelKey: 'settings.section.storageMedia.upload.title',
            descriptionKey: 'settings.section.storageMedia.upload.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'storageMedia.uploadExpiresSeconds',
                labelKey: 'settings.field.storageMedia.uploadExpiresSeconds',
                hintKey: 'settings.field.storageMedia.uploadExpiresSeconds.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'storageMedia.s3PresignDefaultExpiresSeconds',
                labelKey: 'settings.field.storageMedia.s3PresignDefaultExpiresSeconds',
                hintKey: 'settings.field.storageMedia.s3PresignDefaultExpiresSeconds.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'storageMedia.s3PresignMaxExpiresSeconds',
                labelKey: 'settings.field.storageMedia.s3PresignMaxExpiresSeconds',
                hintKey: 'settings.field.storageMedia.s3PresignMaxExpiresSeconds.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'storageMedia.canvasMedia',
            labelKey: 'settings.section.storageMedia.canvasMedia.title',
            descriptionKey: 'settings.section.storageMedia.canvasMedia.description',
            restartRequired: false,
            applyTiming: 'NEXT_INVOCATION',
            fields: [
              {
                path: 'storageMedia.canvasMediaProcessTimeoutMillis',
                labelKey: 'settings.field.storageMedia.canvasMediaProcessTimeoutMillis',
                hintKey: 'settings.field.storageMedia.canvasMediaProcessTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'storageMedia.thumbnailMaxDimension',
                labelKey: 'settings.field.storageMedia.thumbnailMaxDimension',
                hintKey: 'settings.field.storageMedia.thumbnailMaxDimension.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'storageMedia.thumbnailQuality',
                labelKey: 'settings.field.storageMedia.thumbnailQuality',
                hintKey: 'settings.field.storageMedia.thumbnailQuality.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: 100,
                options: null,
              },
            ],
          },
        ],
      },
      {
        key: 'advanced',
        labelKey: 'settings.tabs.advanced',
        descriptionKey: 'settings.section.advanced.description',
        restartRequired: true,
        groups: [
          {
            key: 'advanced.resource',
            labelKey: 'settings.section.advanced.resource.title',
            descriptionKey: 'settings.section.advanced.resource.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'advanced.resourceMaxBytes',
                labelKey: 'settings.field.advanced.resourceMaxBytes',
                hintKey: 'settings.field.advanced.resourceMaxBytes.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'advanced.processor',
            labelKey: 'settings.section.advanced.processor.title',
            descriptionKey: 'settings.section.advanced.processor.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'advanced.processorLeaseDurationMillis',
                labelKey: 'settings.field.advanced.processorLeaseDurationMillis',
                hintKey: 'settings.field.advanced.processorLeaseDurationMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.processorHeartbeatIntervalMillis',
                labelKey: 'settings.field.advanced.processorHeartbeatIntervalMillis',
                hintKey: 'settings.field.advanced.processorHeartbeatIntervalMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.threadResolveFailureDelayMillis',
                labelKey: 'settings.field.advanced.threadResolveFailureDelayMillis',
                hintKey: 'settings.field.advanced.threadResolveFailureDelayMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.modelDispatchBusyFallbackDelayMillis',
                labelKey: 'settings.field.advanced.modelDispatchBusyFallbackDelayMillis',
                hintKey: 'settings.field.advanced.modelDispatchBusyFallbackDelayMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.toolPreflightFailureDelayMillis',
                labelKey: 'settings.field.advanced.toolPreflightFailureDelayMillis',
                hintKey: 'settings.field.advanced.toolPreflightFailureDelayMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.toolDispatchBusyFallbackDelayMillis',
                labelKey: 'settings.field.advanced.toolDispatchBusyFallbackDelayMillis',
                hintKey: 'settings.field.advanced.toolDispatchBusyFallbackDelayMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'advanced.applicationEvent',
            labelKey: 'settings.section.advanced.applicationEvent.title',
            descriptionKey: 'settings.section.advanced.applicationEvent.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'advanced.applicationEventQueueCapacity',
                labelKey: 'settings.field.advanced.applicationEventQueueCapacity',
                hintKey: 'settings.field.advanced.applicationEventQueueCapacity.hint',
                type: 'INTEGER',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.applicationEventMaxBytes',
                labelKey: 'settings.field.advanced.applicationEventMaxBytes',
                hintKey: 'settings.field.advanced.applicationEventMaxBytes.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.applicationEventSendTimeoutMillis',
                labelKey: 'settings.field.advanced.applicationEventSendTimeoutMillis',
                hintKey: 'settings.field.advanced.applicationEventSendTimeoutMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.applicationEventHeartbeatIntervalMillis',
                labelKey: 'settings.field.advanced.applicationEventHeartbeatIntervalMillis',
                hintKey: 'settings.field.advanced.applicationEventHeartbeatIntervalMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
          {
            key: 'advanced.workNotification',
            labelKey: 'settings.section.advanced.workNotification.title',
            descriptionKey: 'settings.section.advanced.workNotification.description',
            restartRequired: true,
            applyTiming: null,
            fields: [
              {
                path: 'advanced.postgresqlWorkNotificationPollMillis',
                labelKey: 'settings.field.advanced.postgresqlWorkNotificationPollMillis',
                hintKey: 'settings.field.advanced.postgresqlWorkNotificationPollMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
              {
                path: 'advanced.postgresqlWorkReconnectBackoffMillis',
                labelKey: 'settings.field.advanced.postgresqlWorkReconnectBackoffMillis',
                hintKey: 'settings.field.advanced.postgresqlWorkReconnectBackoffMillis.hint',
                type: 'LONG',
                nullable: false,
                min: 1,
                max: null,
                options: null,
              },
            ],
          },
        ],
      },
    ],
  }
}
