package fun.fengwk.kkstudio.core.systemsettings;

import org.springframework.stereotype.Component;

import fun.fengwk.kkstudio.share.systemsettings.SystemSettingsSchemaDTO;
import fun.fengwk.kkstudio.share.systemsettings.SystemSettingsSchemaDTO.ApplyTiming;
import fun.fengwk.kkstudio.share.systemsettings.SystemSettingsSchemaDTO.FieldType;

import java.util.List;

/**
 * The single ordered metadata source for editable system settings.
 *
 * <p>Field paths intentionally follow the record component paths and group order follows the
 * existing settings cards. Cross-field constraints remain in {@link SystemSettings}'s canonical
 * constructors; this provider only describes individual editable leaves and their controls.
 */
@Component
public class SystemSettingsSchemaProvider {

  private static final SystemSettingsSchemaDTO SCHEMA = createSchema();

  public SystemSettingsSchemaDTO get() {
    return SCHEMA;
  }

  private static SystemSettingsSchemaDTO createSchema() {
    SystemSettingsSchemaDTO schema = new SystemSettingsSchemaDTO();
    schema.setSections(
        List.of(
            section(
                "aiRuntime",
                "settings.tabs.aiRuntime",
                "settings.section.aiRuntime.description",
                false,
                group(
                    "aiRuntime.retry",
                    "settings.section.aiRuntime.retry.title",
                    "settings.section.aiRuntime.retry.description",
                    false,
                    ApplyTiming.NEXT_INVOCATION,
                    field(
                        "aiRuntime.retryMaxRetries",
                        "settings.field.aiRuntime.retryMaxRetries",
                        null,
                        FieldType.INTEGER,
                        false,
                        0,
                        null),
                    field(
                        "aiRuntime.retryBackoffStrategy",
                        "settings.field.aiRuntime.retryBackoffStrategy",
                        null,
                        FieldType.ENUM,
                        false,
                        null,
                        null,
                        option("FIXED", "settings.option.retryBackoff.fixed"),
                        option("EXPONENTIAL", "settings.option.retryBackoff.exponential")),
                    field(
                        "aiRuntime.retryBaseDelayMillis",
                        "settings.field.aiRuntime.retryBaseDelayMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "aiRuntime.retryMaxDelayMillis",
                        "settings.field.aiRuntime.retryMaxDelayMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null)),
                group(
                    "aiRuntime.compaction",
                    "settings.section.aiRuntime.compaction.title",
                    "settings.section.aiRuntime.compaction.description",
                    false,
                    ApplyTiming.NEXT_INVOCATION,
                    field(
                        "aiRuntime.compactionKeepRecentTokens",
                        "settings.field.aiRuntime.compactionKeepRecentTokens",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "aiRuntime.compactionFallbackModel",
                        "settings.field.aiRuntime.compactionFallbackModel",
                        null,
                        FieldType.MODEL_SELECTION,
                        true,
                        null,
                        null)),
                group(
                    "aiRuntime.subagent",
                    "settings.section.aiRuntime.subagent.title",
                    "settings.section.aiRuntime.subagent.description",
                    false,
                    ApplyTiming.NEXT_INVOCATION,
                    field(
                        "aiRuntime.subagentMaxDepth",
                        "settings.field.aiRuntime.subagentMaxDepth",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "aiRuntime.subagentMaxConcurrency",
                        "settings.field.aiRuntime.subagentMaxConcurrency",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "aiRuntime.subagentMaxTotalConcurrency",
                        "settings.field.aiRuntime.subagentMaxTotalConcurrency",
                        null,
                        FieldType.INTEGER,
                        false,
                        0,
                        null),
                    field(
                        "aiRuntime.subagentIdleTimeoutMillis",
                        "settings.field.aiRuntime.subagentIdleTimeoutMillis",
                        "settings.field.aiRuntime.subagentIdleTimeoutMillis.hint",
                        FieldType.LONG,
                        false,
                        0,
                        null),
                    field(
                        "aiRuntime.subagentMaxTurns",
                        "settings.field.aiRuntime.subagentMaxTurns",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null))),
            section(
                "tool",
                "settings.tabs.toolsPermissions",
                "settings.section.tool.description",
                false,
                group(
                    "tool.permission",
                    "settings.section.tool.permission.title",
                    "settings.section.tool.permission.description",
                    false,
                    ApplyTiming.NEXT_INVOCATION,
                    field(
                        "tool.permission",
                        "settings.section.tool.permission.title",
                        "settings.field.tool.permission.hint",
                        FieldType.PERMISSION,
                        false,
                        null,
                        null,
                        option("allow", "settings.permission.action.allow"),
                        option("ask", "settings.permission.action.ask"),
                        option("deny", "settings.permission.action.deny"))),
                group(
                    "tool.yolo",
                    "settings.section.tool.yolo.title",
                    "settings.section.tool.yolo.description",
                    false,
                    ApplyTiming.NEXT_CHAT,
                    field(
                        "tool.defaultYolo",
                        "settings.field.tool.defaultYolo",
                        null,
                        FieldType.BOOLEAN,
                        false,
                        null,
                        null)),
                group(
                    "tool.gateway",
                    "settings.section.tool.gateway.title",
                    "settings.section.tool.gateway.description",
                    false,
                    ApplyTiming.NEXT_INVOCATION,
                    field(
                        "tool.modelGatewayBusyRetryMillis",
                        "settings.field.tool.modelGatewayBusyRetryMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "tool.toolGatewayBusyRetryMillis",
                        "settings.field.tool.toolGatewayBusyRetryMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "tool.toolGatewayOverloadRetryMillis",
                        "settings.field.tool.toolGatewayOverloadRetryMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "tool.skillLoadTimeoutMillis",
                        "settings.field.tool.skillLoadTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null))),
            section(
                "environment",
                "settings.tabs.environment",
                "settings.section.environment.description",
                false,
                group(
                    "environment.runtime",
                    "settings.section.environment.runtime.title",
                    "settings.section.environment.runtime.description",
                    false,
                    ApplyTiming.NEXT_INVOCATION,
                    field(
                        "environment.maxResourceBytes",
                        "settings.field.environment.maxResourceBytes",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "environment.heartbeatTimeoutMillis",
                        "settings.field.environment.heartbeatTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "environment.directoryListTimeoutMillis",
                        "settings.field.environment.directoryListTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null))),
            section(
                "integrations",
                "settings.tabs.integrations",
                "settings.section.integrations.description",
                true,
                group(
                    "integrations.comfyui",
                    "settings.section.integrations.comfyui.title",
                    "settings.section.integrations.comfyui.description",
                    true,
                    null,
                    field(
                        "integrations.comfyui.enabled",
                        "settings.field.integrations.comfyui.enabled",
                        null,
                        FieldType.BOOLEAN,
                        false,
                        null,
                        null),
                    field(
                        "integrations.comfyui.baseUrl",
                        "settings.field.integrations.comfyui.baseUrl",
                        null,
                        FieldType.TEXT,
                        true,
                        null,
                        null),
                    field(
                        "integrations.comfyui.connectTimeoutMillis",
                        "settings.field.integrations.comfyui.connectTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "integrations.comfyui.readTimeoutMillis",
                        "settings.field.integrations.comfyui.readTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "integrations.comfyui.websocketTimeoutMillis",
                        "settings.field.integrations.comfyui.websocketTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "integrations.comfyui.maxInputFileBytes",
                        "settings.field.integrations.comfyui.maxInputFileBytes",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null)),
                group(
                    "integrations.openCliHub",
                    "settings.section.integrations.openCliHub.title",
                    "settings.section.integrations.openCliHub.description",
                    true,
                    null,
                    field(
                        "integrations.openCliHub.enabled",
                        "settings.field.integrations.openCliHub.enabled",
                        null,
                        FieldType.BOOLEAN,
                        false,
                        null,
                        null),
                    field(
                        "integrations.openCliHub.baseUrl",
                        "settings.field.integrations.openCliHub.baseUrl",
                        null,
                        FieldType.TEXT,
                        true,
                        null,
                        null),
                    field(
                        "integrations.openCliHub.connectTimeoutMillis",
                        "settings.field.integrations.openCliHub.connectTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        120_000),
                    field(
                        "integrations.openCliHub.requestTimeoutMillis",
                        "settings.field.integrations.openCliHub.requestTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1_000,
                        1_800_000),
                    field(
                        "integrations.openCliHub.longPollTimeoutMillis",
                        "settings.field.integrations.openCliHub.longPollTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        121_000,
                        600_000),
                    field(
                        "integrations.openCliHub.streamBufferBytes",
                        "settings.field.integrations.openCliHub.streamBufferBytes",
                        null,
                        FieldType.INTEGER,
                        false,
                        1_024,
                        1_048_576),
                    field(
                        "integrations.openCliHub.maxJsonResponseBytes",
                        "settings.field.integrations.openCliHub.maxJsonResponseBytes",
                        null,
                        FieldType.INTEGER,
                        false,
                        1_024,
                        4_194_304),
                    field(
                        "integrations.openCliHub.maxErrorResponseBytes",
                        "settings.field.integrations.openCliHub.maxErrorResponseBytes",
                        null,
                        FieldType.INTEGER,
                        false,
                        256,
                        65_536),
                    field(
                        "integrations.openCliHub.maxOutputChars",
                        "settings.field.integrations.openCliHub.maxOutputChars",
                        null,
                        FieldType.INTEGER,
                        false,
                        1_024,
                        1_000_000)),
                group(
                    "integrations.seedance",
                    "settings.section.integrations.seedance.title",
                    "settings.section.integrations.seedance.description",
                    true,
                    null,
                    field(
                        "integrations.seedance.enabled",
                        "settings.field.integrations.seedance.enabled",
                        null,
                        FieldType.BOOLEAN,
                        false,
                        null,
                        null),
                    field(
                        "integrations.seedance.workspaceId",
                        "settings.field.integrations.seedance.workspaceId",
                        null,
                        FieldType.TEXT,
                        true,
                        null,
                        256),
                    field(
                        "integrations.seedance.retry",
                        "settings.field.integrations.seedance.retry",
                        null,
                        FieldType.INTEGER,
                        false,
                        0,
                        5),
                    field(
                        "integrations.seedance.hubExecutionTimeoutMillis",
                        "settings.field.integrations.seedance.hubExecutionTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1_000,
                        1_800_000),
                    field(
                        "integrations.seedance.statusPollIntervalMillis",
                        "settings.field.integrations.seedance.statusPollIntervalMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        300_000),
                    field(
                        "integrations.seedance.maxWaitMillis",
                        "settings.field.integrations.seedance.maxWaitMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1_000,
                        14_400_000)),
                group(
                    "integrations.gptImage2",
                    "settings.section.integrations.gptImage2.title",
                    "settings.section.integrations.gptImage2.description",
                    true,
                    null,
                    field(
                        "integrations.gptImage2.paidEnabled",
                        "settings.field.integrations.gptImage2.paidEnabled",
                        null,
                        FieldType.BOOLEAN,
                        false,
                        null,
                        null),
                    field(
                        "integrations.gptImage2.askTimeoutSeconds",
                        "settings.field.integrations.gptImage2.askTimeoutSeconds",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        1_740),
                    field(
                        "integrations.gptImage2.hubExecutionTimeoutMillis",
                        "settings.field.integrations.gptImage2.hubExecutionTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        31_000,
                        1_800_000),
                    field(
                        "integrations.gptImage2.maxWaitMillis",
                        "settings.field.integrations.gptImage2.maxWaitMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1_000,
                        7_200_000)),
                group(
                    "integrations.minimaxH3",
                    "settings.section.integrations.minimaxH3.title",
                    "settings.section.integrations.minimaxH3.description",
                    true,
                    null,
                    field(
                        "integrations.minimaxH3.enabled",
                        "settings.field.integrations.minimaxH3.enabled",
                        null,
                        FieldType.BOOLEAN,
                        false,
                        null,
                        null),
                    field(
                        "integrations.minimaxH3.promptAgentName",
                        "settings.field.integrations.minimaxH3.promptAgentName",
                        null,
                        FieldType.TEXT,
                        true,
                        null,
                        64),
                    field(
                        "integrations.minimaxH3.promptEnvironmentName",
                        "settings.field.integrations.minimaxH3.promptEnvironmentName",
                        null,
                        FieldType.TEXT,
                        true,
                        null,
                        64),
                    field(
                        "integrations.minimaxH3.promptMaxWaitMillis",
                        "settings.field.integrations.minimaxH3.promptMaxWaitMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        1_800_000),
                    field(
                        "integrations.minimaxH3.comfyBaseUrl",
                        "settings.field.integrations.minimaxH3.comfyBaseUrl",
                        null,
                        FieldType.TEXT,
                        true,
                        null,
                        null),
                    field(
                        "integrations.minimaxH3.comfyConnectTimeoutMillis",
                        "settings.field.integrations.minimaxH3.comfyConnectTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        60_000),
                    field(
                        "integrations.minimaxH3.comfyRequestTimeoutMillis",
                        "settings.field.integrations.minimaxH3.comfyRequestTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        300_000),
                    field(
                        "integrations.minimaxH3.comfyPollIntervalMillis",
                        "settings.field.integrations.minimaxH3.comfyPollIntervalMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        60_000),
                    field(
                        "integrations.minimaxH3.comfyMaxWaitMillis",
                        "settings.field.integrations.minimaxH3.comfyMaxWaitMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        7_200_000))),
            section(
                "storageMedia",
                "settings.tabs.storageMedia",
                "settings.section.storageMedia.description",
                true,
                group(
                    "storageMedia.upload",
                    "settings.section.storageMedia.upload.title",
                    "settings.section.storageMedia.upload.description",
                    true,
                    null,
                    field(
                        "storageMedia.uploadExpiresSeconds",
                        "settings.field.storageMedia.uploadExpiresSeconds",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "storageMedia.s3Enabled",
                        "settings.field.storageMedia.s3Enabled",
                        null,
                        FieldType.BOOLEAN,
                        false,
                        null,
                        null),
                    field(
                        "storageMedia.s3PresignDefaultExpiresSeconds",
                        "settings.field.storageMedia.s3PresignDefaultExpiresSeconds",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "storageMedia.s3PresignMaxExpiresSeconds",
                        "settings.field.storageMedia.s3PresignMaxExpiresSeconds",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null)),
                group(
                    "storageMedia.canvasMedia",
                    "settings.section.storageMedia.canvasMedia.title",
                    "settings.section.storageMedia.canvasMedia.description",
                    false,
                    ApplyTiming.NEXT_INVOCATION,
                    field(
                        "storageMedia.canvasMediaProcessTimeoutMillis",
                        "settings.field.storageMedia.canvasMediaProcessTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "storageMedia.thumbnailMaxDimension",
                        "settings.field.storageMedia.thumbnailMaxDimension",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "storageMedia.thumbnailQuality",
                        "settings.field.storageMedia.thumbnailQuality",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        100))),
            section(
                "advanced",
                "settings.tabs.advanced",
                "settings.section.advanced.description",
                true,
                group(
                    "advanced.resource",
                    "settings.section.advanced.resource.title",
                    "settings.section.advanced.resource.description",
                    true,
                    null,
                    field(
                        "advanced.resourceMaxBytes",
                        "settings.field.advanced.resourceMaxBytes",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null)),
                group(
                    "advanced.processor",
                    "settings.section.advanced.processor.title",
                    "settings.section.advanced.processor.description",
                    true,
                    null,
                    field(
                        "advanced.processorLeaseDurationMillis",
                        "settings.field.advanced.processorLeaseDurationMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.processorHeartbeatIntervalMillis",
                        "settings.field.advanced.processorHeartbeatIntervalMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.threadResolveFailureDelayMillis",
                        "settings.field.advanced.threadResolveFailureDelayMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null)),
                group(
                    "advanced.dispatcher",
                    "settings.section.advanced.dispatcher.title",
                    "settings.section.advanced.dispatcher.description",
                    true,
                    null,
                    field(
                        "advanced.modelDispatchBusyFallbackDelayMillis",
                        "settings.field.advanced.modelDispatchBusyFallbackDelayMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.toolPreflightFailureDelayMillis",
                        "settings.field.advanced.toolPreflightFailureDelayMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.toolDispatchBusyFallbackDelayMillis",
                        "settings.field.advanced.toolDispatchBusyFallbackDelayMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.dispatcherLeaseDurationMillis",
                        "settings.field.advanced.dispatcherLeaseDurationMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.dispatcherPollIntervalMillis",
                        "settings.field.advanced.dispatcherPollIntervalMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.dispatcherRejectionDelayMillis",
                        "settings.field.advanced.dispatcherRejectionDelayMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.dispatcherMaxDispatchTasks",
                        "settings.field.advanced.dispatcherMaxDispatchTasks",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "advanced.dispatcherWorkerConcurrency",
                        "settings.field.advanced.dispatcherWorkerConcurrency",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "advanced.dispatcherWorkerQueueCapacity",
                        "settings.field.advanced.dispatcherWorkerQueueCapacity",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null)),
                group(
                    "advanced.canvas",
                    "settings.section.advanced.canvas.title",
                    "settings.section.advanced.canvas.description",
                    true,
                    null,
                    field(
                        "advanced.canvasFunctionExecutorCoreSize",
                        "settings.field.advanced.canvasFunctionExecutorCoreSize",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "advanced.canvasFunctionExecutorMaxSize",
                        "settings.field.advanced.canvasFunctionExecutorMaxSize",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "advanced.canvasFunctionExecutorQueueCapacity",
                        "settings.field.advanced.canvasFunctionExecutorQueueCapacity",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null)),
                group(
                    "advanced.applicationEvent",
                    "settings.section.advanced.applicationEvent.title",
                    "settings.section.advanced.applicationEvent.description",
                    true,
                    null,
                    field(
                        "advanced.applicationEventQueueCapacity",
                        "settings.field.advanced.applicationEventQueueCapacity",
                        null,
                        FieldType.INTEGER,
                        false,
                        1,
                        null),
                    field(
                        "advanced.applicationEventMaxBytes",
                        "settings.field.advanced.applicationEventMaxBytes",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.applicationEventSendTimeoutMillis",
                        "settings.field.advanced.applicationEventSendTimeoutMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.applicationEventHeartbeatIntervalMillis",
                        "settings.field.advanced.applicationEventHeartbeatIntervalMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null)),
                group(
                    "advanced.workNotification",
                    "settings.section.advanced.workNotification.title",
                    "settings.section.advanced.workNotification.description",
                    true,
                    null,
                    field(
                        "advanced.postgresqlWorkNotificationPollMillis",
                        "settings.field.advanced.postgresqlWorkNotificationPollMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null),
                    field(
                        "advanced.postgresqlWorkReconnectBackoffMillis",
                        "settings.field.advanced.postgresqlWorkReconnectBackoffMillis",
                        null,
                        FieldType.LONG,
                        false,
                        1,
                        null)))));
    return schema;
  }

  private static SystemSettingsSchemaDTO.SectionDTO section(
      String key,
      String labelKey,
      String descriptionKey,
      boolean restartRequired,
      SystemSettingsSchemaDTO.GroupDTO... groups) {
    SystemSettingsSchemaDTO.SectionDTO section = new SystemSettingsSchemaDTO.SectionDTO();
    section.setKey(key);
    section.setLabelKey(labelKey);
    section.setDescriptionKey(descriptionKey);
    section.setRestartRequired(restartRequired);
    section.setGroups(List.of(groups));
    return section;
  }

  private static SystemSettingsSchemaDTO.GroupDTO group(
      String key,
      String labelKey,
      String descriptionKey,
      boolean restartRequired,
      ApplyTiming applyTiming,
      SystemSettingsSchemaDTO.FieldDTO... fields) {
    SystemSettingsSchemaDTO.GroupDTO group = new SystemSettingsSchemaDTO.GroupDTO();
    group.setKey(key);
    group.setLabelKey(labelKey);
    group.setDescriptionKey(descriptionKey);
    group.setRestartRequired(restartRequired);
    group.setApplyTiming(applyTiming);
    group.setFields(List.of(fields));
    return group;
  }

  private static SystemSettingsSchemaDTO.FieldDTO field(
      String path,
      String labelKey,
      String hintKey,
      FieldType type,
      boolean nullable,
      Integer min,
      Integer max,
      SystemSettingsSchemaDTO.OptionDTO... options) {
    SystemSettingsSchemaDTO.FieldDTO field = new SystemSettingsSchemaDTO.FieldDTO();
    field.setPath(path);
    field.setLabelKey(labelKey);
    field.setHintKey(hintKey != null ? hintKey : labelKey + ".hint");
    field.setType(type);
    field.setNullable(nullable);
    field.setMin(min);
    field.setMax(max);
    field.setOptions(options.length == 0 ? null : List.of(options));
    return field;
  }

  private static SystemSettingsSchemaDTO.OptionDTO option(String value, String labelKey) {
    SystemSettingsSchemaDTO.OptionDTO option = new SystemSettingsSchemaDTO.OptionDTO();
    option.setValue(value);
    option.setLabelKey(labelKey);
    return option;
  }
}
