spring:

  application:
    # 应用名称
    name: kk-studio

  profiles:
    active: dev

  mvc:
    converters:
      # spring mvc使用的json转换器，使用规约指定的gson
      # jackson JacksonHttpMessageConvertersConfiguration
      # gson GsonHttpMessageConvertersConfiguration
      preferred-json-mapper: jackson

  # mysql连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 替换为mysql {host}、{port}、{database}
    url: jdbc:mysql://{host}:{port}/{database}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&connectTimeout=3000&socketTimeout=3000&useSSL=false
    # 替换为mysql {username}
    username: {username}
    # 替换为mysql {password}
    password: {password}

server:
  port: 8080
  # Compression
  compression:
    # 启用gzip压缩
    enabled: true

# https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus,offline,online"

# 日志配置
logging:
  level:
    root: info

# 规约配置
convention:
  snowflake-id:
    # 雪花id开始时间，固定不可变
    initial-timestamp: 1702214261706
    # 当前 MVP 固定 worker id，不依赖 Redis 申请 worker id
    worker-id: 0

  i18n:
    # i18n properties文件名称
    base-name: string
    # 使用语言
    locale: zh_CN

  code:
    i18n:
      # 错误码i18n语言，与i18n.locale保持一致
      locale: ${convention.i18n.locale}
