package fun.fengwk.kkstudio.harness.environment.daemon;

/** Daemon wire 协议的消息类型。 */
public enum DaemonMessageType {
  HELLO,
  READY,
  HEARTBEAT,
  STARTED,
  PROGRESS,
  COMPLETED,
  FAILED,
  CANCELLED,
  WELCOME,
  TEMPORARY_RESOURCE_POLICY,
  INVOKE,
  CANCEL,
  RESOURCE_UPLOAD_REQUEST,
  RESOURCE_UPLOAD_TICKET,
  RESOURCE_UPLOAD_COMMIT,
  SHELL_COMMAND,
  SHELL_EVENT,
  UPDATE,
  UPDATE_RESULT,
  ERROR
}
