package fun.fengwk.kkstudio.core.agent.run.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import fun.fengwk.kkstudio.core.CoreTestApplication;
import fun.fengwk.kkstudio.core.agent.runtime.service.AgentRunRuntimeService;
import fun.fengwk.kkstudio.core.agent.session.service.AgentSessionService;
import fun.fengwk.kkstudio.core.testing.StubProviderManager;
import fun.fengwk.kkstudio.share.model.AgentRunDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionCreateDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionEventDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionMessageCreateDTO;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import fun.fengwk.kkstudio.core.CoreTestApplication;
import fun.fengwk.kkstudio.core.agent.runtime.service.AgentRunRuntimeService;
import fun.fengwk.kkstudio.core.agent.session.service.AgentSessionService;
import fun.fengwk.kkstudio.core.testing.StubProviderManager;
import fun.fengwk.kkstudio.share.model.AgentRunDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionCreateDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionEventDTO;
import fun.fengwk.kkstudio.share.model.AgentSessionMessageCreateDTO;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * @author fengwk
 */
@SpringBootTest(classes = CoreTestApplication.class)
public class AgentRunServiceTest {

  private static final Set<String> TERMINAL_STATUSES = Set.of("succeeded", "failed");

  @Autowired private AgentSessionService agentSessionService;

  @Autowired private AgentRunService agentRunService;

  @Autowired private AgentRunRuntimeService agentRunRuntimeService;

  @Autowired private StubProviderManager stubProviderManager;

  @BeforeEach
  public void resetStubProviderManager() {
    stubProviderManager.reset();
  }

  private void waitForRunCompleted(String runId) throws InterruptedException {
    long deadline = System.currentTimeMillis() + 5000L;
    while (System.currentTimeMillis() < deadline) {
      AgentRunDTO run = agentRunService.getRun(runId);
      if (run != null && TERMINAL_STATUSES.contains(run.getStatus())) {
        return;
      }
      Thread.sleep(50L);
    }
    throw new AssertionError("run did not reach terminal status within 5s: " + runId);
  }

  @Test
  public void shouldListQueuedRunsCreatedByMessageSubmit() throws InterruptedException {
    stubProviderManager.enqueueText("Generated by runtime");

    AgentSessionCreateDTO createSessionDTO = new AgentSessionCreateDTO();
    createSessionDTO.setAgentName("default-assistant");
    createSessionDTO.setTitle("Run Session");

    AgentSessionDTO session = agentSessionService.createSession(createSessionDTO);

    AgentSessionMessageCreateDTO createMessageDTO = new AgentSessionMessageCreateDTO();
    createMessageDTO.setContent("Generate a queued run");

    AgentSessionEventDTO createdEvent =
        agentSessionService.createMessage(session.getSessionId(), createMessageDTO);
    agentRunRuntimeService.scheduleQueuedRun(
        createdEvent.getRunId(), session.getSessionId(), createMessageDTO.getContent());
    waitForRunCompleted(createdEvent.getRunId());

    assertNotNull(createdEvent.getRunId());
    assertTrue(createdEvent.getRunId().startsWith("rn_"));

    List<AgentRunDTO> runs = agentRunService.listRuns(session.getSessionId());
    assertEquals(1, runs.size());

    AgentRunDTO run = runs.get(0);
    assertEquals(createdEvent.getRunId(), run.getRunId());
    assertEquals(session.getSessionId(), run.getSessionId());
    assertEquals(createdEvent.getEventId(), run.getTriggerEventId());
    assertEquals("succeeded", run.getStatus());
    assertNotNull(run.getCreateTime());
    assertNotNull(run.getUpdateTime());
  }

  @Test
  public void shouldCompleteRunWhenProviderCallbackIsAsync() throws InterruptedException {
    stubProviderManager.enqueueAsyncText("Generated asynchronously");

    AgentSessionCreateDTO createSessionDTO = new AgentSessionCreateDTO();
    createSessionDTO.setAgentName("default-assistant");
    createSessionDTO.setTitle("Async Run Session");
    AgentSessionDTO session = agentSessionService.createSession(createSessionDTO);

    AgentSessionMessageCreateDTO createMessageDTO = new AgentSessionMessageCreateDTO();
    createMessageDTO.setContent("Generate an async run");
    AgentSessionEventDTO createdEvent =
        agentSessionService.createMessage(session.getSessionId(), createMessageDTO);
    agentRunRuntimeService.scheduleQueuedRun(
        createdEvent.getRunId(), session.getSessionId(), createMessageDTO.getContent());
    waitForRunCompleted(createdEvent.getRunId());

    List<AgentRunDTO> runs = agentRunService.listRuns(session.getSessionId());
    assertEquals(1, runs.size());
    assertEquals(createdEvent.getRunId(), runs.get(0).getRunId());
    assertEquals("succeeded", runs.get(0).getStatus());
  }

  @Test
  public void shouldCreateAndTransitionQueuedRunDirectly() {
    AgentSessionCreateDTO createSessionDTO = new AgentSessionCreateDTO();
    createSessionDTO.setAgentName("default-assistant");
    createSessionDTO.setTitle("Manual Run Session");
    AgentSessionDTO session = agentSessionService.createSession(createSessionDTO);

    AgentRunDTO createdRun =
        agentRunService.createQueuedRun(
            "rn_manual_transition", session.getSessionId(), "ev_manual_trigger");
    assertEquals("rn_manual_transition", createdRun.getRunId());
    assertEquals(session.getSessionId(), createdRun.getSessionId());
    assertEquals("ev_manual_trigger", createdRun.getTriggerEventId());
    assertEquals("queued", createdRun.getStatus());

    assertEquals("queued", agentRunService.getRun("rn_manual_transition").getStatus());
    assertTrue(agentRunService.markRunning("rn_manual_transition"));
    assertEquals("running", agentRunService.getRun("rn_manual_transition").getStatus());
    assertTrue(agentRunService.markSucceeded("rn_manual_transition"));
    assertEquals("succeeded", agentRunService.getRun("rn_manual_transition").getStatus());
    assertFalse(agentRunService.markFailed("rn_manual_transition"));
    assertNull(agentRunService.getRun("rn_missing"));
  }

  @Test
  public void shouldDetectActiveRunsBySession() {
    AgentSessionCreateDTO createSessionDTO = new AgentSessionCreateDTO();
    createSessionDTO.setAgentName("default-assistant");
    createSessionDTO.setTitle("Active Run Session");
    AgentSessionDTO session = agentSessionService.createSession(createSessionDTO);

    assertFalse(agentRunService.hasActiveRun(session.getSessionId()));

    agentRunService.createQueuedRun("rn_active_probe", session.getSessionId(), "ev_active_probe");
    assertTrue(agentRunService.hasActiveRun(session.getSessionId()));

    assertTrue(agentRunService.markRunning("rn_active_probe"));
    assertTrue(agentRunService.hasActiveRun(session.getSessionId()));

    assertTrue(agentRunService.markSucceeded("rn_active_probe"));
    assertFalse(agentRunService.hasActiveRun(session.getSessionId()));
  }

  @Test
  public void shouldRejectInvalidRunArguments() {
    AgentSessionCreateDTO createSessionDTO = new AgentSessionCreateDTO();
    createSessionDTO.setAgentName("default-assistant");
    createSessionDTO.setTitle("Invalid Run Session");
    AgentSessionDTO session = agentSessionService.createSession(createSessionDTO);

    assertThrows(
        IllegalArgumentException.class,
        () -> agentRunService.createQueuedRun(null, session.getSessionId(), "ev_trigger"));
    assertThrows(
        IllegalArgumentException.class,
        () -> agentRunService.createQueuedRun("rn_invalid_session", " ", "ev_trigger"));
    assertThrows(
        IllegalArgumentException.class,
        () -> agentRunService.createQueuedRun("rn_invalid_trigger", session.getSessionId(), " "));
    assertThrows(
        IllegalArgumentException.class,
        () -> agentRunService.createQueuedRun("rn_missing_session", "se_missing", "ev_trigger"));
    assertThrows(IllegalArgumentException.class, () -> agentRunService.getRun(" "));
    assertThrows(IllegalArgumentException.class, () -> agentRunService.markRunning(null));
    assertThrows(IllegalArgumentException.class, () -> agentRunService.listRuns(" "));
    assertThrows(IllegalArgumentException.class, () -> agentRunService.hasActiveRun(" "));
  }
}
